matrix:
  TERRAFORM_VERSION:
    - 0.12.25
  TERRAGRUNT_VERSION:
    - 0.23.12

pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-docker-terragrunt
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    context: app
    dockerfile: app/Dockerfile
    force_tag: true
    build_args:
      - TERRAFORM_VERSION=${TERRAFORM_VERSION}
      - TERRAGRUNT_VERSION=${TERRAGRUNT_VERSION}
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
      - v${TERRAGRUNT_VERSION}
    when:
      event: push
